# Base para iniciar a documentação
site_name: Apresentação MkDocs
site_description: Apresentação do MkDocs no A3Tech
site_author: Nilson Cunha
copyright: MkDocs - Apresentação A3Tech
nav:
    - Bem-vindo: index.md
    - Antes de começar: pergunta.md
    - Sobre documentação:
        - Como encontrei o mkdocs: 'sobre_mkdocs/sobre.md'
        - Por quê mkdocs?: 'mkdocs.md'
        - Markdown: markdown.md
        - Instalação: instalacao.md
theme:
    #name: mkdocs
    #name: readthedocs
    name: material
# -----------------------------------
# Estilizações na documentação
    language: pt
    favicon: img/a3_icon.ico
    logo: img/a3_icon.ico
    features: 
      - search.suggest
      - search.highlight
    palette:
      - scheme: default
        primary: teal
        accent: pink
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
      - scheme: slate
        primary: purple
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2 # Nível básico dos cabeçalhos
        separator: "_"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys

# docs_dir: docs # caso deseje trocar o nome do diretório principal 
